# Generated by Django 5.2.4 on 2025-08-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="decscription",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
